export class Title { }
export class Text { }
export class Logo { }
export class Image { }
export class Link { }
export class ClassList { }
export class Button { }
export class GalleryItem { }
export class StyleObject { }
export class Icon { }
export class Label { }
export class Cost { }
export class Delimiter { }
export class VideoElement { }
export class Timer { }
export class ProductSection { }
export class Form { }

export class GallerySlider { }
export class AvailablePlatforms { }
export class AgeRestrictions { }
export class SocialNetworks { }
export class Slogan { }
export class SystemRequirements { }
export class TextInherit { }
export class IconWithText { }
