export class Title { }
export class Text { }
export class Logo { }
export class Image { }
export class Link { }
export class ClassList { }
export class Button { }
export class GalleryItem { }
export class StyleObject { }
export class Icon { }
export class Product { }
export class Label { }
export class Cost { }
export class ImageNoResize { }
export class Delimiter { }
export class Video { }
export class ProductSection { }

export class GallerySlider { }
export class AvailablePlatforms { }
export class AgeRestrictions { }
export class SocialNetworks { }
export class Slogan { }
export class SystemRequirements { }
