import './gallery'
import './gallery1'
// import './gallery2'
import './galleryPopup'
import './galleryCarousel'
import './tabs'
import './productExtend'
import './video'
import './videoPopup'
import './element-link'
import './element-toggle'
import './cookies-policy'
import './sectionsGroups'
import './mobile-menu'
import './fix-empty-href'
import './timer'
import './scroll-into-section'
import './forms'
